### ISSUE TITLE
Clicking on the caption button inserts the text "undefined"

### ISSUE THREAD

**Issue by W3Extensions** [StudioJunkyard/summernote-image-captionit#1]
...Also, the caption icon doesn't show up when I view the image controls. However, I can click on the empty space that's supposed to be the caption button label.

 I don't really see what I could be screwing up. Is there a working example I could look at?

**Comment by ghost** [comment]
There's no working example, I didn't think it was necessary.
You can change the icon to whatever you wish to use.
The 'appears' if there is no `title` or `alt` information contained in the image. You can simply edit the text that appears. I may actually do something so it shows something else, rather than `undefinded` so user know it can be edited.

**Comment by W3Extensions** [comment]
Thanks for the really fast reply.

Okay, so I didn't realize "undefined" was meant to be the caption text. Something like "Caption goes here" would be more useful.  I added dashed border around the figcaptionClass so it hopefully stands out as something meant to be edited. (I had expected a popover form prompting me to enter caption text--I think quill.js or one of those scripts does that, but your approach makes more sense.)

However, there are a few issues I noticed.

1) The image popover remains, blocking the view caption text after it is inserted. (I have to click away to get rid of the popover.) 

2) The image float functionality is rendered useful when inside a figure, perhaps the image popover alignment controls could apply to the figure element when applicable.

3) Also, I still can't get the default caption icon to appear. But custom HTML works fine.

4) And deleting an image should delete the outer figure tag and the HTML within.

Anyway, even with the issues I've mentioned, your plugin is much appreciated.

**Comment by ghost** [comment]
Cheers, glad you find it handy.
1. The popover is actually the Summernote Popover which has the button added too it.
2. That's a good idea, I'll look into that. I usually use an `img-repsonsive` class on the image, and use the `col-XX-X` Bootstrap sizing classes to adjust the size of the figure, and have the image size change accordingly.
3. In my own instance I use an SVG icon from another project I maintain called LibreICONS, by using `<i class="note-icon">{SVG here}</i>`, you can see this in other plugins I've made for Summernote.
4. Another good idea, I'm now wondering if I can capture Summernote's delete action, check if it's an image being removed, and if so also remove the `figure` and `figcaption` elements.

Thanks for the suggestions, it's always good to add more features and improve things.

**Comment by DennisSuitters** [comment]
Sorry, it's been so long, life kind of got in the way.
I discovered that the icon doesn't appear due to the svg element not containing width or height attributes with values.
I'll experiment with the removing the figure, and figcaption tags when deleting images.

**Comment by DennisSuitters** [comment]
I took a different approach with removing the `figure` and `figcaption` elements. If clicking the CaptionIt button on an image that already contains `figure` the plugin will remove those elements, or rather toggle them.
